
branches:
 only:
  - travis-ci-experiment

language: cpp
os: linux
dist: trusty

addons:
 apt:
  sources:
   - sourceline: 'ppa:ubuntu-toolchain-r/test'
  packages:
   - gcc-5
   - g++-5

compiler:
 - gcc

script:
 - g++ TravisCiTest.cpp
