
branches:
 only:
  - travis-ci-experiment

language: cpp
dist: trusty

matrix:
 include:
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5
    env:
   #  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
     - C_COMPILER=gcc-5
     - CXX_COMPILER=g++-5
     - CACHE_FILE="ReleaseGcc.cmake"
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
      packages:
       - clang-3.8
    env:
    # - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
     - C_COMPILER=clang-3.8
     - CXX_COMPILER=clang++-3.8

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
 - sudo apt-get -qq update
 # - eval "${CXX}"
 # - eval "${MATRIX_EVAL}"
 
install:
 - sudo apt-get install -y cmake
 - sudo apt-get install -y libboost-dev
 - yes | sudo apt-get install -y qt58base qt58x11extras qt58imageformats qt58svg qt58tools

script:
 - echo ${CACHE_FILE}
 - ${C_COMPILER} --version
 - ${CXX_COMPILER} --version
 - ${CXX_COMPILER} TravisCiTest.cpp --std=c++14
 - mkdir build
 - cd build
 - cmake -C ../cmake/caches/${CACHE_FILE} -D CMAKE_C_COMPILER=${C_COMPILER} -D CMAKE_CXX_COMPILER=${CXX_COMPILER} -D QT_PREFIX_PATH=/opt/qt58 ..
 - make -j4
 - make test
