
branches:
 only:
  - master

git:
 submodules: false

language: cpp
dist: trusty

matrix:
 include:
  # GCC Debug
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5
    env:
     - C_COMPILER=gcc-5
     - CXX_COMPILER=g++-5
     - CACHE_FILE="DebugGcc.cmake"
  # GCC Release
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5
    env:
     - C_COMPILER=gcc-5
     - CXX_COMPILER=g++-5
     - CACHE_FILE="ReleaseGcc.cmake"
  # Clang Debug
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
      packages:
       - clang-3.8
       # Have to install a recent version of libstdc++ (and available libc++ seems not to support C++14?)
       - g++-5
    env:
     - C_COMPILER=clang-3.8
     - CXX_COMPILER=clang++-3.8
     - CACHE_FILE="DebugClang.cmake"
  # Clang Release
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
      packages:
       - clang-3.8
       # Have to install a recent version of libstdc++ (and available libc++ seems not to support C++14?)
       - g++-5
    env:
     - C_COMPILER=clang-3.8
     - CXX_COMPILER=clang++-3.8
     - CACHE_FILE="ReleaseClang.cmake"

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
 - sudo apt-get -qq update

install:
 - sudo apt-get install -y cmake
 - sudo apt-get install -y libboost-dev
 - yes | sudo apt-get install -y qt58base qt58x11extras qt58imageformats qt58svg qt58tools

script:
 - mkdir build
 - cd build
 - cmake -C ../cmake/caches/${CACHE_FILE} -D CMAKE_C_COMPILER=${C_COMPILER} -D CMAKE_CXX_COMPILER=${CXX_COMPILER} -D QT_PREFIX_PATH=/opt/qt58 ..
 - make -j4
 - make test
