
branches:
 only:
  - travis-ci-experiment

language: cpp
dist: trusty

matrix:
 include:
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
      packages:
       - g++-5
       - cmake
       - libboost-dev
    env:
     - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
     apt:
      sources:
       - ubuntu-toolchain-r-test
       - llvm-toolchain-precise-3.8
      packages:
       - clang-3.8
       - cmake
       - libboost-dev
    env:
     - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"


before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt58-trusty
 - sudo apt-get -qq update
 - eval "${MATRIX_EVAL}"
 
install:
 - sudo apt-get install --yes qt58-meta-minimal

script:
 - ${CXX} TravisCiTest.cpp --std=c++14
