
#branches:
 #only:
  #- master

#git:
 #submodules: false

environment:

  matrix:
    # MinGW
    - CMAKE_GENERATOR: "MinGW Makefiles"

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # Thanks to: http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%

build_script:
  - mkdir build
  - cd build
  - cmake -C ..\cmake\caches\ReleaseGcc.cmake -G "%CMAKE_GENERATOR%" ..\
