
branches:
 only:
  - master

environment:

  BOOST_ROOT: 'C:\Libraries'

  matrix:
    # MinGW
    - CMAKE_GENERATOR: "MinGW Makefiles"
      QT_PREFIX_PATH: 'C:\Qt\5.9.1\mingw53_32'
      MINGW_PREFIX_PATH: 'C:\Qt\Tools\mingw530_32'

before_build:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  # Thanks to: http://help.appveyor.com/discussions/problems/3193-cmake-building-for-mingw-issue-with-git-shexe
  - set PATH=%PATH:C:\Program Files\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%QT_PREFIX_PATH%\bin;%MINGW_PREFIX_PATH%\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -C ..\cmake\caches\ReleaseGcc.cmake -G "%CMAKE_GENERATOR%" ..\
  - cmake --build . -- -j4

test_script:
  - ctest .
